#!/usr/bin/env bash
#this installs nginx and configures another server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
file=/etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i 's|^server {|server {\n\tadd_header X-Served-By $hostname;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n|g' $file
sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' $file
sudo service nginx restart
