#!/usr/bin/env bash
# installs the load balancer
apt-get update
apt-get -y install haproxy=1.5.\* -t trusty-backports
sed -i "s/ENABLED=0/ENABLED=1"/ /etc/default/haproxy
sed -i "\$a listen appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 489-web-01 34.73.60.145 check\n\tserver 489-web-02 35.185.44.189 check" /etc/haproxy/haproxy.cfg
service haproxy start
