#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
c=0
h=0
t=0
while [ $t -le 779 ]
do
    if  [ $(( $c % 60 )) -eq 0 ]
    then
	echo "Hour:" $h
	h=$(( $h + 1 ))
	c=1
    else
	echo $c
	c=$(( $c + 1 ))
    fi
    t=$(( $t + 1 ))
done
