#!/usr/bin/env bash
# This script is giving info of file Holbertonschool
flnm=holbertonschool
if [ -e $flnm ]
then
    echo "holbertonschool file exists"
    if [ -s $flnm ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f $flnm ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
