#!/usr/bin/env bash
#this installs nginx then makes a 301 redirect
sudo apt-get update
sudo apt-get -y install nginx
FILE='/etc/nginx/sites-available/default'
sed -i 's|^server {|server{\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n|g' $file
service nginx restart
