#!/usr/bin/env bash
# makes custome 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
file=/etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' $file
sudo service nginx restart
